-- nz-system 测试用 H2 建表脚本
-- H2 MODE=PostgreSQL 下运行，每次测试启动时重建

DROP TABLE IF EXISTS sys_message;
DROP TABLE IF EXISTS sys_social;
DROP TABLE IF EXISTS sys_file_config;
DROP TABLE IF EXISTS sys_role_menu;
DROP TABLE IF EXISTS sys_user_post;
DROP TABLE IF EXISTS sys_user_role;
DROP TABLE IF EXISTS sys_login_log;
DROP TABLE IF EXISTS sys_oper_log;
DROP TABLE IF EXISTS sys_dict_data;
DROP TABLE IF EXISTS sys_dict_type;
DROP TABLE IF EXISTS sys_menu;
DROP TABLE IF EXISTS sys_user;
DROP TABLE IF EXISTS sys_role;
DROP TABLE IF EXISTS sys_dept;

CREATE TABLE sys_dept
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT,
    name        VARCHAR(100) NOT NULL,
    sort        INT          DEFAULT 0,
    status      INT          DEFAULT 0,
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_user
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL DEFAULT 1,
    username    VARCHAR(50)  NOT NULL,
    password    VARCHAR(100),
    nickname    VARCHAR(50),
    email       VARCHAR(100),
    phone       VARCHAR(20),
    phone_hash  VARCHAR(64),
    dept_id     BIGINT,
    status      INT          DEFAULT 0,
    gender      VARCHAR(1)   DEFAULT '2',
    avatar_file_id BIGINT,
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_social
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL DEFAULT 1,
    user_id          BIGINT       NOT NULL,
    provider         VARCHAR(64)  NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    username         VARCHAR(200),
    nickname         VARCHAR(200),
    email            VARCHAR(320),
    avatar           VARCHAR(1000),
    create_time      TIMESTAMP,
    update_time      TIMESTAMP,
    UNIQUE (tenant_id, provider, provider_user_id),
    UNIQUE (tenant_id, user_id, provider)
);

CREATE TABLE sys_message
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL DEFAULT 1,
    user_id     BIGINT       NOT NULL,
    sender_id   BIGINT,
    category    VARCHAR(32)  NOT NULL,
    type        VARCHAR(32)  NOT NULL DEFAULT 'message',
    source      VARCHAR(64)  NOT NULL DEFAULT 'backend',
    title       VARCHAR(200) NOT NULL,
    summary     VARCHAR(500),
    content     CLOB         NOT NULL,
    data_json   CLOB,
    path        VARCHAR(500),
    read_status SMALLINT     NOT NULL DEFAULT 0,
    read_time   TIMESTAMP,
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_role
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    role_key    VARCHAR(50),
    sort        INT          DEFAULT 0,
    status      INT          DEFAULT 0,
    remark      VARCHAR(500),
    data_scope  INT          DEFAULT 1,
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_menu
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT,
    name        VARCHAR(100),
    path        VARCHAR(200),
    component   VARCHAR(200),
    icon        VARCHAR(100),
    sort        INT          DEFAULT 0,
    type        VARCHAR(20),
    perm        VARCHAR(100),
    visible     INT          DEFAULT 1,
    status      INT          DEFAULT 0,
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_dict_type
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100),
    type        VARCHAR(100),
    status      INT          DEFAULT 0,
    remark      VARCHAR(500),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_dict_data
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_type   VARCHAR(100),
    label       VARCHAR(100),
    value       VARCHAR(100),
    sort        INT          DEFAULT 0,
    status      INT          DEFAULT 0,
    remark      VARCHAR(500),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_user_role
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL
);

CREATE TABLE sys_user_post
(
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL
);

CREATE TABLE sys_role_menu
(
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL
);

CREATE TABLE sys_oper_log
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(128) NOT NULL,
    business_type  SMALLINT,
    oper_content   VARCHAR(255),
    method         VARCHAR(255),
    request_method VARCHAR(50),
    oper_name      VARCHAR(64),
    oper_url       VARCHAR(255),
    oper_ip        VARCHAR(128),
    user_agent     VARCHAR(500),
    oper_param     CLOB,
    json_result    CLOB,
    status         SMALLINT     DEFAULT 0,
    error_msg      CLOB,
    oper_time      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sys_login_log
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT,
    username   VARCHAR(64),
    ip         VARCHAR(128),
    status     SMALLINT  DEFAULT 0,
    msg        VARCHAR(255),
    login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sys_file_config
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_name             VARCHAR(100) NOT NULL,
    storage_type            VARCHAR(16) NOT NULL,
    base_path               VARCHAR(500),
    endpoint                VARCHAR(500),
    access_key_id           VARCHAR(200),
    access_key_secret       VARCHAR(1000),
    bucket_name             VARCHAR(200),
    region                  VARCHAR(100),
    domain                  VARCHAR(500),
    path_prefix             VARCHAR(200),
    local_access_url_prefix VARCHAR(200),
    max_file_size_bytes     BIGINT NOT NULL DEFAULT 104857600,
    status                  SMALLINT NOT NULL DEFAULT 1,
    remark                  VARCHAR(500),
    create_time             TIMESTAMP,
    update_time             TIMESTAMP
);