-- nz-system 测试用 H2 建表脚本
-- H2 MODE=PostgreSQL 下运行，每次测试启动时重建

DROP TABLE IF EXISTS sys_role_menu;
DROP TABLE IF EXISTS sys_user_role;
DROP TABLE IF EXISTS sys_login_log;
DROP TABLE IF EXISTS sys_oper_log;
DROP TABLE IF EXISTS sys_dict_data;
DROP TABLE IF EXISTS sys_dict_type;
DROP TABLE IF EXISTS sys_menu;
DROP TABLE IF EXISTS sys_user;
DROP TABLE IF EXISTS sys_role;
DROP TABLE IF EXISTS sys_dept;

CREATE TABLE sys_dept
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT,
    name        VARCHAR(100) NOT NULL,
    sort        INT          DEFAULT 0,
    status      INT          DEFAULT 0,
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_user
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50)  NOT NULL,
    password    VARCHAR(100),
    nickname    VARCHAR(50),
    email       VARCHAR(100),
    phone       VARCHAR(20),
    dept_id     BIGINT,
    status      INT          DEFAULT 0,
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_role
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    role_key    VARCHAR(50),
    sort        INT          DEFAULT 0,
    status      INT          DEFAULT 0,
    remark      VARCHAR(500),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_menu
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT,
    name        VARCHAR(100),
    path        VARCHAR(200),
    component   VARCHAR(200),
    icon        VARCHAR(100),
    sort        INT          DEFAULT 0,
    type        VARCHAR(20),
    perm        VARCHAR(100),
    visible     INT          DEFAULT 1,
    status      INT          DEFAULT 0,
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_dict_type
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100),
    type        VARCHAR(100),
    status      INT          DEFAULT 0,
    remark      VARCHAR(500),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_dict_data
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_type   VARCHAR(100),
    label       VARCHAR(100),
    value       VARCHAR(100),
    sort        INT          DEFAULT 0,
    status      INT          DEFAULT 0,
    remark      VARCHAR(500),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE TABLE sys_user_role
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL
);

CREATE TABLE sys_role_menu
(
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL
);

CREATE TABLE sys_oper_log
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(128) NOT NULL,
    business_type  SMALLINT,
    oper_content   VARCHAR(255),
    method         VARCHAR(255),
    request_method VARCHAR(50),
    oper_name      VARCHAR(64),
    oper_url       VARCHAR(255),
    oper_ip        VARCHAR(128),
    user_agent     VARCHAR(500),
    oper_param     CLOB,
    json_result    CLOB,
    status         SMALLINT     DEFAULT 0,
    error_msg      CLOB,
    oper_time      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sys_login_log
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT,
    username   VARCHAR(64),
    ip         VARCHAR(128),
    status     SMALLINT  DEFAULT 0,
    msg        VARCHAR(255),
    login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
