server:
  port: 8080

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 120MB

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

nz:
  file:
    storage-type: local
    max-file-size-bytes: 104857600

sa-token:
  token-name: Authorization
  timeout: 86400
  active-timeout: -1
  is-concurrent: true
  token-style: uuid
  is-log: false
