import * as userApi from './user'
import * as deptApi from './dept'
import * as roleApi from './role'
import * as postApi from './post'
import * as configApi from './config'
import * as noticeApi from './notice'
import * as fileApi from './file'
import * as dictApi from './dict'
import * as workbenchApi from './workbench'
import * as monitorApi from './monitor'
import * as onlineApi from './online'
import * as realtimeApi from './realtime'
import * as smsApi from './sms'
import * as moduleApi from './modules'

export { userApi, deptApi, roleApi, postApi, configApi, noticeApi, fileApi, dictApi, workbenchApi, monitorApi, onlineApi, realtimeApi, smsApi, moduleApi }

export type { SysUser, UserQuery } from './user'
export type { SysDept } from './dept'
export type { SysRole } from './role'
export type { SysPost } from './post'
export type { SysConfig } from './config'
export type { SysNotice, NoticeQuery } from './notice'
export type { SysFile, FileQuery } from './file'
export type { SysDictType, SysDictData, DictTypeQuery } from './dict'
export type { WorkbenchSnapshot, LoginLogRow, OperLogRow } from './workbench'
export type { MonitorSummary } from './monitor'
export type { OnlineUser, OnlineUserQuery } from './online'
export type { RealtimeConnectionStats, RealtimeEnvelope, RealtimeTicket, RealtimeTransport } from './realtime'
export type { SmsChannel, SmsTemplate, SmsSendLog } from './sms'
