DROP TABLE IF EXISTS sys_role_menu;
DROP TABLE IF EXISTS sys_user_role;
DROP TABLE IF EXISTS sys_menu;
DROP TABLE IF EXISTS sys_role;
DROP TABLE IF EXISTS sys_user;
DROP TABLE IF EXISTS sys_dept;
DROP TABLE IF EXISTS sys_tenant;
DROP TABLE IF EXISTS sys_client;
DROP TABLE IF EXISTS sys_config;
DROP TABLE IF EXISTS sys_post;
DROP TABLE IF EXISTS sys_login_log;
DROP TABLE IF EXISTS sys_oper_log;

CREATE TABLE sys_tenant
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code VARCHAR(32) NOT NULL UNIQUE,
    tenant_name VARCHAR(128) NOT NULL,
    contact_user VARCHAR(64),
    contact_phone VARCHAR(20),
    package_id BIGINT NOT NULL,
    expire_time TIMESTAMP,
    account_count INTEGER NOT NULL DEFAULT 100,
    status SMALLINT NOT NULL DEFAULT 0,
    remark VARCHAR(500),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sys_client
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id VARCHAR(64) NOT NULL UNIQUE,
    client_name VARCHAR(128) NOT NULL,
    login_type VARCHAR(32) NOT NULL,
    token_timeout INTEGER NOT NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    remark VARCHAR(500),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sys_dept
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    parent_id BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(64) NOT NULL,
    sort INTEGER DEFAULT 0,
    status SMALLINT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sys_user
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    dept_id BIGINT,
    username VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL,
    phone_hash VARCHAR(64),
    nickname VARCHAR(64),
    email VARCHAR(1000),
    phone VARCHAR(1000),
    status SMALLINT DEFAULT 0,
    gender VARCHAR(16),
    avatar_file_id BIGINT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, username)
);

CREATE TABLE sys_role
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    name VARCHAR(64) NOT NULL,
    role_key VARCHAR(64) NOT NULL,
    sort INTEGER DEFAULT 0,
    status SMALLINT DEFAULT 0,
    remark VARCHAR(500),
    data_scope INTEGER NOT NULL DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, role_key)
);

CREATE TABLE sys_menu
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT DEFAULT 0,
    name VARCHAR(64) NOT NULL,
    path VARCHAR(200),
    component VARCHAR(255),
    icon VARCHAR(64),
    sort INTEGER DEFAULT 0,
    type CHAR(1),
    perm VARCHAR(128),
    visible SMALLINT DEFAULT 0,
    status SMALLINT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sys_user_role
(
    tenant_id BIGINT NOT NULL DEFAULT 1,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE sys_role_menu
(
    tenant_id BIGINT NOT NULL DEFAULT 1,
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, menu_id)
);

CREATE TABLE sys_config
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    config_name VARCHAR(128) NOT NULL,
    config_key VARCHAR(128) NOT NULL,
    config_value VARCHAR(500),
    config_type SMALLINT DEFAULT 2,
    status SMALLINT DEFAULT 0,
    remark VARCHAR(500),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, config_key)
);

CREATE TABLE sys_post
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    post_code VARCHAR(64) NOT NULL,
    post_name VARCHAR(64) NOT NULL,
    sort INTEGER DEFAULT 0,
    status SMALLINT DEFAULT 0,
    remark VARCHAR(500),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, post_code)
);

CREATE TABLE sys_login_log
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    user_id BIGINT,
    username VARCHAR(64),
    ip VARCHAR(128),
    status SMALLINT DEFAULT 0,
    msg VARCHAR(255),
    login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sys_oper_log
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    title VARCHAR(128) NOT NULL,
    business_type SMALLINT,
    oper_content VARCHAR(255),
    method VARCHAR(255),
    request_method VARCHAR(16),
    oper_name VARCHAR(64),
    oper_url VARCHAR(255),
    oper_ip VARCHAR(128),
    user_agent VARCHAR(500),
    oper_param CLOB,
    json_result CLOB,
    status SMALLINT DEFAULT 0,
    error_msg CLOB,
    oper_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO sys_tenant (id, tenant_code, tenant_name, contact_user, package_id, account_count, status, remark)
VALUES (1, 'default', 'E2E 默认租户', '管理员', 1, 100, 0, 'H2 E2E seed');

INSERT INTO sys_client (id, client_id, client_name, login_type, token_timeout, status)
VALUES (1, 'nz-web-account', 'E2E Web 账号登录', 'account', 7200, 0);

INSERT INTO sys_dept (id, tenant_id, parent_id, name, sort, status)
VALUES (1, 1, 0, '总公司', 0, 0);

INSERT INTO sys_user (id, tenant_id, dept_id, username, password, nickname, status)
VALUES (1, 1, 1, 'admin', '$2a$10$9U.FFaB9V1A4mjaD01fFAuE/Dle0Q3fvrrRqb9vQaFdggBNjL/LCS', '管理员', 0);

INSERT INTO sys_role (id, tenant_id, name, role_key, sort, status, data_scope)
VALUES (1, 1, '超级管理员', 'admin', 0, 0, 1);

INSERT INTO sys_menu (id, parent_id, name, path, component, icon, sort, type, perm, visible, status) VALUES
    (900, 0, '工作台', 'workbench', 'workbench/index', 'House', -10, 'C', 'system:workbench:view', 0, 0),
    (1000, 0, '系统管理', '/system', NULL, 'Setting', 0, 'M', NULL, 0, 0),
    (1500, 1000, '岗位管理', 'post', 'system/post/index', 'User', 5, 'C', 'system:post:list', 0, 0),
    (1511, 1500, '新增岗位', NULL, NULL, NULL, 1511, 'F', 'system:post:add', 0, 0),
    (1700, 1000, '参数管理', 'config', 'system/config/index', 'Tools', 7, 'C', 'system:config:list', 0, 0),
    (1711, 1700, '新增参数', NULL, NULL, NULL, 1711, 'F', 'system:config:add', 0, 0);

INSERT INTO sys_user_role (tenant_id, user_id, role_id) VALUES (1, 1, 1);
INSERT INTO sys_role_menu (tenant_id, role_id, menu_id)
SELECT 1, 1, id FROM sys_menu;

INSERT INTO sys_post (id, tenant_id, post_code, post_name, sort, status, remark)
VALUES (1, 1, 'dev', '开发工程师', 1, 0, 'H2 E2E seed');

INSERT INTO sys_config (id, tenant_id, config_name, config_key, config_value, config_type, status, remark)
VALUES (1, 1, '主框架页签', 'sys.index.tabs', 'true', 1, 0, 'H2 E2E seed');

CREATE TABLE IF NOT EXISTS sys_role_dept (tenant_id BIGINT DEFAULT 1 NOT NULL, role_id BIGINT NOT NULL, dept_id BIGINT NOT NULL, PRIMARY KEY(tenant_id, role_id, dept_id));

CREATE TABLE IF NOT EXISTS sys_user_post (
    tenant_id BIGINT NOT NULL DEFAULT 1,
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    PRIMARY KEY (tenant_id, user_id, post_id)
);
