DROP TABLE IF EXISTS sys_file_config;

CREATE TABLE sys_file_config
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id               BIGINT NOT NULL DEFAULT 1,
    config_name             VARCHAR(100) NOT NULL,
    storage_type            VARCHAR(16) NOT NULL,
    base_path               VARCHAR(500),
    endpoint                VARCHAR(500),
    access_key_id           VARCHAR(200),
    access_key_secret       VARCHAR(1000),
    bucket_name             VARCHAR(200),
    region                  VARCHAR(100),
    domain                  VARCHAR(500),
    path_prefix             VARCHAR(200),
    local_access_url_prefix VARCHAR(200),
    max_file_size_bytes     BIGINT NOT NULL DEFAULT 104857600,
    status                  SMALLINT NOT NULL DEFAULT 1,
    remark                  VARCHAR(500),
    create_time             TIMESTAMP,
    update_time             TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_role_dept (tenant_id BIGINT DEFAULT 1 NOT NULL, role_id BIGINT NOT NULL, dept_id BIGINT NOT NULL, PRIMARY KEY(tenant_id, role_id, dept_id));
